site_name: "James Glass, PhD"
site_url: https://thewritingtimes.blog

theme:
  name: material
  font:
    text: Merriweather Sans
  logo: assets/james2.png
  favicon: assets/james1.png
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - navigation.tabs.sticky
    - navigation.indexes 
    - toc.follow
    - navigation.expand
    - navigation.path
    - search.share
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - toc.integrate
   
   
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep-purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep-orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Experience: experience.md
  - Training & Development:
      - Courses: courses/training-and-development.md
  - Education:
      - PhD: education/phd.md
      - Masters: education/masters.md
      - BSc Mechatronics: education/bsc-mechatronics.md
      - BSc Screen Practice: education/bsc-screen-practice.md
  - Examples of Work:
      - CAD Trends: examples/cad-trends.md
      - CAD Software: examples/cad-software.md
      - Start with elecworks: examples/start-with-elecworks.md
  - API Example: api example/online-order-api.md
  - Diagrams: diagrams.md
  - Dashboard: 
      - Dashboard Example One: dashboard/dashboard-example-one.md
      - Dashboard Example Two: dashboard/dashboard-example-two.md
  - References: references/quotes.md

  

extra:
  analytics:
    provider: google
    property: G-DFB5D1HK5Q
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/james-glass-phd-206b7b3/

extra_css:
  - assets/stylesheets/extra.css
  
copyright: "Copyright Â© 2025 James Glass"



